name: Publish Container Images

on:
  push:
    branches: [ buildplugin ]
  schedule:
    - cron: 0 5 * * *

jobs:
  publish-container-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout redhat-developer/rhdh-plugins
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          repository: redhat-developer/rhdh-plugins
          persist-credentials: false

      - name: Set up Node
        uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/ # Needed for auth

      - name: Login to Quay.io
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}
          registry: quay.io
      - name: Build ai-integrations plugin
        run: |
          cd workspaces/ai-integrations
          yarn install
          yarn tsc
          npx --yes @janus-idp/cli@latest package package-dynamic-plugins --use-docker --tag quay.io/redhat-ai-dev/ai-integrations-rhdh:latest
      - name: Push latest ai-integrations plugin to Quay.io
        run: |
          docker push quay.io/redhat-ai-dev/ai-integrations-rhdh:latest
      - name: Tag with git commit sha and push to Quay.io
        run: |
          GIT_SHA=$(git rev-parse HEAD)
          docker tag quay.io/redhat-ai-dev/ai-integrations-rhdh:latest quay.io/redhat-ai-dev/ai-integrations-rhdh:${GIT_SHA}
          docker push quay.io/redhat-ai-dev/ai-integrations-rhdh:${GIT_SHA}